after-login-command   = []
after-startup-command = []

# Start AeroSpace at login
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# The 'accordion-padding' specifies the size of accordion padding
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner) and between monitor edges (outer).
[gaps]
inner.horizontal = 30
inner.vertical   = 30
outer.left       = 30
outer.bottom     = 30
outer.top        = 30
outer.right      = 30

[mode.main.binding]
# Layout Split  
alt-t = 'layout tiles'
alt-a = 'layout accordion'

# Focus commands  
cmd-left  = 'focus left'
cmd-down  = 'focus down'
cmd-up    = 'focus up'
cmd-right = 'focus right'

# Move commands  
alt-left  = 'move left'
alt-down  = 'move down'
alt-up    = 'move up'
alt-right = 'move right'

# Move to Workspaces   
alt-g = 'workspace G' # GoodNotes 
alt-h = 'workspace H' # Home 
alt-m = 'workspace M' # Music
alt-n = 'workspace N' # Notes 
alt-s = 'workspace S' # Safari
alt-w = 'workspace W' # WezTerm
alt-y = 'workspace Y' # YouTube

# Moving node to Workspace  
cmd-alt-g = 'move-node-to-workspace G'
cmd-alt-h = 'move-node-to-workspace H'
cmd-alt-m = 'move-node-to-workspace M'
cmd-alt-n = 'move-node-to-workspace N'
cmd-alt-s = 'move-node-to-workspace S'
cmd-alt-w = 'move-node-to-workspace W'
cmd-alt-y = 'move-node-to-workspace Y'

# Sevice Mode  
alt-shift-s = 'mode service'

# 'service' binding mode declaration.
[mode.service.binding]
r = ['reload-config', 'mode main']
