format = """
[╭](fg:current_line)\
$os\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$java\
$c\
$cmd_duration\
$time\
$username\
$line_break\
$character\
"""

palette = 'coolnight'
add_newline = true

[palettes.coolnight]
foreground   = '#CBE0F0'
background   = '#011423'
current_line = '#446A85'
primary      = '#011423'
box          = '#446A85'
blue         = '#81D4FA'
cyan         = '#A0EAF7'
green        = '#81C784'
orange       = '#FFB74D'
pink         = '#FF8A80'
purple       = '#B39DDB'
red          = '#E57373'
yellow       = '#FFF176'

[os]
format = '(fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan)'
disabled = false

[os.symbols]
Android     = ''
Arch        = ''
Debian      = ''
Fedora      = ''
Linux       = ''
Macos       = ''
OracleLinux = '⊂⊃'
Ubuntu      = ''
Unknown     = ''
Windows     = ''

[directory]
format = '[─](fg:current_line)[](fg:pink)[󰷏](fg:primary bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = " ~/"
truncation_symbol = ' '
truncation_length = 4
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)[](fg:box)'
symbol = ''

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙'

[python]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ''

[java]
format = '[─](fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ''

[c]
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ''

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[time]
format = '[─](fg:current_line)[](fg:purple)[󰦖](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%I:%M %p'
disabled = false

[username]
format = '[─](fg:current_line)[](fg:yellow)[](fg:primary bg:yellow)[](fg:yellow bg:box)[ $user](fg:foreground bg:box)[](fg:box) '
show_always = true

[character]
format = """
[╰─](fg:current_line)[$symbol](bold)"""
success_symbol = '[❯](fg:green)'
error_symbol   = '[✗](fg:red)'

[git_status]
format = '[─](fg:current_line)[](fg:green)[$all_status$ahead_behind](fg:primary bg:green)[](fg:green bg:box)'
conflicted = "[=](fg:red)"
ahead = "[⇡${count}](fg:blue)"
behind = "[⇣${count}](fg:blue)"
diverged = "[⇡⇣${count}](fg:yellow)"
up_to_date = ""
untracked = "[?${count}](fg:red)"
stashed = "[$${count}](fg:yellow)"
modified = "[!${count}](fg:yellow)"
staged = "[+${count}](fg:green)"
renamed = "[»${count}](fg:blue)"
deleted = "[✘${count}](fg:red)"

