"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 2, 3, 9 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false 
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 4000
max_height      = 3500
image_delay     = 30
image_quality   = 75
sixel_fraction  = 10

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" }
]
open = [
    { run = 'open "$@"', desc = "Open", for = "macos" }
]
reveal = [
    { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
    { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" }
]
play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" }
]

[open]
rules = [
    { name = "*/", use = [ "edit", "open", "reveal" ] },
    { mime = "text/*", use = [ "edit", "reveal" ] },
    { mime = "image/*", use = [ "open", "reveal" ] },
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
    { mime = "application/json", use = [ "edit", "reveal" ] },
    { mime = "*/javascript", use = [ "edit", "reveal" ] },
    { name = "*", use = [ "open", "reveal" ] }
]

[tasks]
micro_workers    = 10
macro_workers    = 10
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]

[input]
cursor_blink = false

# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = [ "Create:", "Create (dir):" ]
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# filter
filter_title  = "Filter:"
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

[confirm]
trash_title  = "Trash {n} selected file{s}?"
trash_origin = "center"
trash_offset = [ 0, 0, 70, 20 ]

quit_title   = "Quit?"
quit_content = "Tasks are still running, sure to quit?"
quit_origin  = "center"
quit_offset  = [ 0, 0, 50, 15 ]
